### ISSUE TITLE
Usage outside TensorFlow

### ISSUE THREAD

**Issue by rhysstubbs** [atanasster/hyperparameters#2]
Hi - Can this library only be used with TensorFlow?

**Comment by atanasster** [comment]
Hi - no its not tied to tensorflow, but currently most of the examples are based on tensorflow.

What other library do you have in mind?

**Comment by rhysstubbs** [comment]
For my undergraduate dissertation I am comparing hyper-parameter optimisation algorithms, so I wanted a framework/library that could be independently used. I will be integrating it with a Neuroevolution algorithm to evolve the ANNs hyper-parameters.

**Comment by atanasster** [comment]
Good luck, let us know if your dissertation is available online.

**Comment by ifeLight** [comment]
Why only fmin, what of fmax functions

**Comment by rhysstubbs** [comment]
@atanasster I completely forgot about this thread until now.

I won't link to the full disertation, but I submitted a condensed version to the [UKCI 2019 conference](https://www.ukci2019.port.ac.uk/) and you can find that version on the [Bournemouth Univerisity Website](http://eprints.bournemouth.ac.uk/32508/1/UKCI2019_Paper__Rhys_.pdf).

I can't quite remember as it was over a year ago now but I'm not actually sure if I used this library, another or rolled my own. Either way, nice work!
